---
# tasks file for dhcp
- name: "packages"
  package:
    name: "{{ item }}"
  with_items:
    - "{{ dhcp_packages }}"
  tags:
    - dhcp
    - packages

- name: "Listening interface(s)"
  lineinfile:
    dest: '{{ dhcp_default_file }}'
    regexp: '^INTERFACESv4=".*"'
    line: "INTERFACESv4=\"{{ dhcp_interfaces | default(ansible_default_ipv4['interface']) }}\""
  when:
    - not ansible_check_mode
  notify:
    - dhcpd restart
  tags:
    - dhcp
    - interfaces

- name: "DHCPDv4_CONF"
  lineinfile:
    dest: '{{ dhcp_default_file }}'
    regexp: '.*DHCPDv4_CONF=.*'
    line: "DHCPDv4_CONF={{ dhcp_dhcpd4_config_file }}"
  when:
    - not ansible_check_mode
    - dhcp_dhcpd4_config_file is defined
  notify:
    - dhcpd restart
  tags:
    - dhcp
    - v4conf

- name: "config file"
  template:
    # TODO # dhcpd-primary.conf.j2 and dhcpd-secondary.conf.j2 are the same ! refactorize !
    src: 'dhcpd-{{ dhcp_role }}.conf.j2'
    dest: "{{ dhcp_dhcpd4_config_file | default('/etc/dhcp/dhcpd.conf') }}"
  notify:
    - dhcpd restart
  tags:
    - dhcp
    - config

- name: "shared config file"
  template:
    src: 'dhcpd-shared.conf.j2'
    dest: "{{ dhcp_failover_shared_config_file }}"
  notify:
    - dhcpd restart
  tags:
    - dhcp
    - config
...
